drop table if exists users cascade;
drop table if exists requests cascade;
drop table if exists items cascade;
drop table if exists bookings cascade;
drop table if exists comments cascade;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

create table if not exists items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description  VARCHAR(512) NOT NULL,
  owner_id BIGINT NOT NULL,
  is_available Boolean NOT NULL,
  FOREIGN KEY (owner_id) references users (id) on delete cascade,
  CONSTRAINT pk_item PRIMARY KEY (id)
);

create table if not exists bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date timestamp without time zone not null,
    end_date   timestamp without time zone not null,
    item_id    BIGINT,
    booker_id  BIGINT,
    status     varchar(100)                not null,
    CONSTRAINT pk_booking PRIMARY KEY (id),
    FOREIGN KEY (booker_id) references users (id) on delete cascade,
    FOREIGN KEY (item_id) references items (id) on delete cascade
);

create table if not exists comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text      varchar(255)                not null,
    item_id   BIGINT,
    author_id BIGINT,
    created   timestamp without time zone not null,
    CONSTRAINT pk_comment PRIMARY KEY (id),
    FOREIGN KEY (author_id) references users (id) on delete cascade,
    FOREIGN KEY (item_id) references items (id) on delete cascade
);